fix: repeated removing cause crash
kronenthaler/mod-pbxproj pull request #310
Opened 2021-09-27 09:21 UTC by LZYongcn

2021-10-04 07:53 UTC, kronenthaler commented
Can you provide an example of when this happens?

2021-10-18 06:38 UTC, LZYongcn commented
> Can you provide an example of when this happens?
> or can you provide a unit test for it?

It is happened when there are two files with same file name, the 'target' will be removed twice from 'potential_targets', the second time will throw an exception. Actually, I think only check the file name is not strict, files with the same file name may not be the same file. I'm not a professional Python developer，i'm sorry i don't know what should i do next.

2022-01-04 15:06 UTC, kronenthaler requested changes

2022-01-04 15:06 UTC, kronenthaler commented on pbxproj/pbxextensions/ProjectFiles.py
> +            _check_file()
```suggestion
            for build_phase_id in target.buildPhases:
                build_phase = self.get_object(build_phase_id)
                for build_file_id in build_phase.files:
                    build_file = self.get_object(build_file_id)
                    if build_file is None:
                        continue

                    file_ref = self.get_object(build_file.fileRef)
                    if 'path' in file_ref and ProjectFiles._path_leaf(path) == ProjectFiles._path_leaf(file_ref.path) and target in potential_targets:
                        potential_targets.remove(target)
```

2022-01-04 15:08 UTC, merged